name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - publishToSubfolder

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install node modules
        run: npm ci

      - name: Install node modules
        run: npm run test

      - name: Build
        run: npm run build

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ steps.vars.outputs.short_ref }}
